# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Directory Site Maker
publisher: Directories Near Me
email: michael.joseph.miller@gmail.com
logo: /assets/images/logo.svg
logo_icon: icons/logo.svg
place_focus: directory
place_type: Directory Site # used in liquid as singular or plural i.e. steakhouse(s)
description: >- # this means to ignore newlines until "baseurl:"
  Replace with site discription
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.steakhouse-near-me.us' # the site's hostname & protocol, e.g. http://example.com

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-seo-tag:
  defaults:
    og:type: website

header_pages:
  - index.html
  - search.html
  - about.md
  - contact.html

keywords:

collections:
  states:
    output: true
  cities:
    output: true
  places:
    output: true

exclude:
  - gemfiles/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - _backend/
  - README.md
  - package.json
  - package-lock.json
  - eslint.config.js
